name: CMake on a single platform

on:
  push:
    branches: [ "main", "workflow" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    # container:
    #   image: kunlinyu/dbus2http:latest
    #   options: --user root

    steps:
    - uses: actions/checkout@v4

    - name: Docker pull
      run: docker pull kunlinyu/dbus2http:latest

    - name: Debug
      run: pwd && ls -l
        
    - name: Conan Install
      run: docker run dus2http --rm \
        -v ${{ github.workspace }}:workspace \
        -w workspace \
        /bin/bash -c "
          conan install . --profile:host=docker/conan/profile_host_x86_64.txt
        "

    - name: Configure CMake
      run: docker run dus2http --rm \
        -v ${{ github.workspace }}:workspace \
        -w workspace \
        /bin/bash -c "
          cmake --preset x86_64-Release
        "

    - name: Build
      run: docker run dus2http --rm \
        -v ${{ github.workspace }}:workspace \
        -w workspace \
        /bin/bash -c "
          cmake --build --preset x86_64-Release
        "
