name: CMake on a single platform

on:
  push:
    branches: [ "main", "workflow" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    # container:
    #   image: kunlinyu/dbus2http:latest
    #   options: --user root

    steps:
    - uses: actions/checkout@v4

    # - name: Docker pull
    #   run: docker pull kunlinyu/dbus2http:latest

    - name: Debug
      run: pwd && ls -l && whoami && id
        
    - name: Conan Install
      run: docker run --rm -v ${{ github.workspace }}:/home/ubuntu/workspace -w /home/ubuntu/workspace kunlinyu/dbus2http /bin/bash -c " pwd && ls -l && whoami  "
