name: CMake on a single platform

on:
  push:
    branches: [ "main", "workflow" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-in-container:
    runs-on: ubuntu-latest
    container:
      image: kunlinyu/dbus2http:latest
      options: --user root

    steps:
    - uses: actions/checkout@v4
      with:
        path: /home/ubuntu/workspace/dbus2http

    - name: Debug
      run: pwd && ls -l
        
    - name: Conan Install
      run: conan install . --build=missing --profile:build=/home/ubuntu/.conan2/profiles/default --profile:host=docker/conan/profile_host_x86_64.txt

    - name: Configure CMake
      run: cmake --preset x86_64-Release

    - name: Build
      run: cmake --build --preset x86_64-Release
